sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk latex-xcolor texlive-latex-extra texlive-lang-spanish chktex lacheck
script:
- make all
- lacheck *.tex
- chktex -q *.tex 2>/dev/null | tee lint.out
- test ! -s lint.out
